import Sidebar from "@/components/common/Sidebar.jsx";
import Navbar from "@/components/common/Navbar.jsx";
import FeedbackPopup from "@/components/common/FeedbackPopup";

import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen w-full">
          <Sidebar />

          <main className="flex-1 ml-0 min900:ml-64 flex flex-col">
            <Navbar />

            <div className="flex-1 overflow-y-auto p-6">{children}</div>
          </main>
        </div>

        <FeedbackPopup />
      </body>
    </html>
  );
}
